name: Run Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**/**']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.10'

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Unit tests
        run: bun test

      - name: Checks
        run: bun check:all
