name: Unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**/**']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.10'

      - name: Install Dependencies
        run: bun install --frozen-lockfile
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: bun test
  check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: bun check
